import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { PageIntro } from "@/components/site-chrome";
import astrologyWheel from "@/assets/astrology-wheel.jpg";
import tarotHands from "@/assets/tarot-hands.jpg";
import onlineReading from "@/assets/online-reading.jpg";
export const Route = createFileRoute("/blog")({head:()=>({meta:[{title:"The Astral Journal | Astral Tarot 24"},{name:"description",content:"Tarot card meanings, astrology guidance, and spiritual wisdom for everyday life."},{property:"og:title",content:"The Astral Journal | Astral Tarot 24"},{property:"og:description",content:"Insights and wisdom from Astral Tarot 24."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:BlogPage});
const posts=[{cat:"Tarot Meanings",title:"The Fool: Embracing New Beginnings Without Fear",img:tarotHands,text:"The Fool is the most misunderstood card in the Major Arcana. Far from representing foolishness, it carries the energy of pure potential."},{cat:"Astrology",title:"Mercury Retrograde: What It Actually Means for You",img:astrologyWheel,text:"There is more to Mercury retrograde than communication breakdowns and old situations returning."},{cat:"Tarot & Astrology",title:"Reading the Moon: How Lunar Phases Amplify Your Tarot Practice",img:onlineReading,text:"The moon has guided mystics, farmers, and lovers for millennia. Aligning your tarot practice adds deeper rhythm."},{cat:"Tarot Meanings",title:"The Tower Card: Why Destruction Is Sometimes the Greatest Gift",img:tarotHands,text:"No card creates more fear than The Tower. Yet its message is one of release, truth, and renewal."},{cat:"Astrology",title:"Venus in Your Birth Chart: Love, Beauty, and What You Truly Value",img:astrologyWheel,text:"Venus reveals how you attract and experience love, what brings you joy, and what you consider beautiful."},{cat:"Practice & Ritual",title:"How to Build a Daily Tarot Practice That Actually Sticks",img:onlineReading,text:"A daily tarot practice is one of the most transformative habits a seeker can develop."}];
function BlogPage(){const [filter,setFilter]=useState("All");const categories=["All","Tarot Meanings","Astrology","Tarot & Astrology","Practice & Ritual"];const visible=filter==="All"?posts:posts.filter(p=>p.cat===filter);return <main><PageIntro eyebrow="Insights & wisdom" title="The Astral Journal" copy="Tarot card meanings, astrology guides, and spiritual wisdom to illuminate your everyday path."/><section className="section-space"><div className="mx-auto max-w-5xl px-5"><article className="panel mb-16 grid overflow-hidden md:grid-cols-2"><img src={tarotHands} alt="Tarot cards for The Fool article" width={1200} height={800} className="h-full min-h-72 w-full object-cover"/><div className="flex flex-col justify-center p-8"><p className="eyebrow">Featured · Tarot meanings</p><h2 className="mt-4 font-display text-2xl uppercase">The Fool: Embracing New Beginnings Without Fear</h2><p className="mt-4 leading-7 text-muted-foreground">The Fool carries the energy of pure potential — the moment before the first step, when anything is still possible.</p><span className="mt-6 text-sm uppercase text-primary">Read article →</span></div></article><div className="mb-8 flex flex-wrap justify-center gap-2">{categories.map(c=><button key={c} onClick={()=>setFilter(c)} className={`rounded-full border px-4 py-2 font-display text-[.62rem] uppercase transition ${filter===c?"border-primary bg-primary text-primary-foreground":"border-border bg-card text-muted-foreground hover:border-primary"}`}>{c}</button>)}</div><div className="grid gap-6 md:grid-cols-3">{visible.map(p=><article className="panel overflow-hidden" key={p.title}><div className="relative"><img src={p.img} alt="" width={1200} height={800} loading="lazy" className="h-40 w-full object-cover opacity-60"/><span className="eyebrow absolute left-4 top-4 rounded bg-background/80 px-2 py-1 text-[.55rem]">{p.cat}</span></div><div className="p-6"><p className="text-xs text-muted-foreground">September 15, 2026 · 6 min read</p><h2 className="mt-3 font-display text-base uppercase leading-6">{p.title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{p.text}</p><p className="mt-5 text-xs uppercase text-primary">Read article →</p></div></article>)}</div></div></section></main>}
