import { createFileRoute, Link } from "@tanstack/react-router";
import { ChevronDown } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CallToAction, services } from "@/components/site-content";
import { PageIntro, SectionHeading } from "@/components/site-chrome";

export const Route = createFileRoute("/services")({ staticData:{sitemap:true}, head: () => ({ meta: [{ title: "Tarot Reading Services | Astral Tarot 24" }, { name: "description", content: "Choose a personal tarot, astrology, or online reading with Astral Tarot 24." }, { property: "og:title", content: "Tarot Reading Services | Astral Tarot 24" }, { property: "og:description", content: "Personal tarot and astrology readings for clarity and guidance." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ServicesPage });

function ServicesPage(){ return <main><PageIntro eyebrow="Sacred offerings" title="Choose Your Path to Clarity" copy="Every reading is a sacred conversation between you, the cards, and the cosmos. Find the session that speaks to your soul."/><section className="section-space"><div className="mx-auto max-w-5xl space-y-12 px-5">{services.map((s,i)=><article key={s.title} className="panel grid overflow-hidden md:grid-cols-2"><img src={s.image} alt={s.title} width={1200} height={800} loading="lazy" className={`h-full min-h-72 w-full object-cover ${i%2 ? "md:order-2" : ""}`}/><div className="flex flex-col justify-center p-7 md:p-10"><p className="eyebrow">{s.eyebrow}</p><h2 className="mt-3 font-display text-2xl uppercase text-foreground">{s.title}</h2><p className="mt-4 leading-7 text-muted-foreground">{s.desc}</p><ul className="mt-5 space-y-2 text-sm text-muted-foreground"><li>✦ Personal guidance and clarity</li><li>✦ Space for your deepest questions</li><li>✦ Practical insights for moving forward</li></ul><div className="mt-7 flex flex-wrap items-end justify-between gap-5"><div className="text-sm"><span className="text-muted-foreground">{s.duration}</span><strong className="ml-5 text-lg text-primary">{s.price}</strong></div><Button asChild variant="celestial" size="sm"><Link to="/contact">Book this reading</Link></Button></div></div></article>)}</div></section><HowItWorks/><Faq/><CallToAction/></main> }

function HowItWorks(){const steps=[["01","Book your session"],["02","Set your intention"],["03","The reading"],["04","Integration & follow-up"]];return <section className="section-space bg-deep/60"><div className="mx-auto max-w-4xl px-5"><SectionHeading eyebrow="The journey" title="How a reading works" copy="Your first step toward insight, clarity, and meaningful answers."/><div className="grid gap-5 sm:grid-cols-2">{steps.map(([n,t])=><div className="panel p-7" key={n}><span className="font-display text-3xl text-primary/60">{n}</span><h3 className="mt-4 font-display uppercase">{t}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">A thoughtful, private experience designed to meet you exactly where you are.</p></div>)}</div></div></section>}
function Faq(){const qs=[["Do I need to believe in tarot for it to work?","No. An open mind and willingness to reflect are all you need."],["How should I prepare for my reading?","Bring one or two clear intentions, and choose a calm space where you can be present."],["Are online readings as accurate as in-person?","Yes. Intuition and insight are not limited by physical distance."],["Can tarot predict the future?","Tarot illuminates patterns and possibilities, helping you make empowered choices."],["How often should I get a reading?","Whenever you reach a crossroads or feel ready for fresh perspective."]];return <section className="section-space"><div className="mx-auto max-w-2xl px-5"><SectionHeading eyebrow="Questions" title="Frequently Asked Questions"/>{qs.map(([q,a])=><details className="panel mb-3 p-5" key={q}><summary className="flex items-center justify-between font-display text-sm uppercase">{q}<ChevronDown className="size-4 text-primary"/></summary><p className="pt-4 text-muted-foreground">{a}</p></details>)}</div></section>}